local map = require("utils").map

map("n", "<leader>gg", ":G <CR>")
map("n", "<leader>bd", ":bd <CR>")
map("n", "<leader>q", ":q <CR>")
map("n", "<leader>w", ":w <CR>")
map("n", "<leader>aw", ":wa <CR>")
map("i", "kj", "<ESC>")
map("n", "<leader>e", ":NeoTreeFocusToggle <CR>")
map("n", "<C-l>", "<C-w>l")
map("n", "<C-j>", "<C-w>j")
map("n", "<C-h>", "<C-w>h")
map("n", "<C-k>", "<C-w>k")
map("n", "<leader>h", ":nohlsearch <CR>", { silent = true })
map("n", "<leader>t", ":TroubleToggle workspace_diagnostics <CR>", { silent = true })
map("n", "<leader>ff", "<cmd>lua require('telescope.builtin').find_files({ hidden = true })<cr>")
map("n", "<leader>fg", "<cmd>lua require('telescope.builtin').live_grep()<cr>")
map("n", "<leader>fb", "<cmd>lua require('telescope.builtin').buffers()<cr>")
map("n", "<leader>fh", "<cmd>lua require('telescope.builtin').help_tags()<cr>")
map("n", "<leader>fq", "<cmd>lua require('telescope.builtin').quickfix()<cr>")
map("n", "<leader>fs", "<cmd>lua require('telescope.builtin').grep_string()<cr>")
map("n", "<leader>fd", "<cmd>lua require('telescope.builtin').current_buffer_fuzzy_find()<cr>")
map("n", "<leader>fo", "<cmd>lua require('telescope.builtin').oldfiles()<cr>")
map("n", "<leader>fr", "<cmd>lua require('telescope.builtin').lsp_references()<cr>")
map("n", "<leader>ft", "<cmd>lua require('telescope.builtin').lsp_document_symbols()<cr>")
map("n", "<leader>fi", "<cmd>lua require('telescope.builtin').diagnostics()<cr>")
map("n", "<leader>rv", ":source $MYVIMRC<cr>", { silent = true })
